### ISSUE TITLE
increasing precision

### ISSUE THREAD

**Issue by MarkSwanson** [mamrhein/fpdec.rs#1]
I'd like to use this library with the 'quantities' crate to do some quantum mechanics work.
Planck's constant is 6.62607015 × 10−34 , so I'd like about 42 digits of precision.

Is forking this library the only way to increase the precision?
(Fork and adjust the MAX_N_FRAC_DIGITS constant defined here: fpdec-core/src/lib.rs)

Thanks!

**Comment by MarkSwanson** [comment]
Sorry, I read the exponent min/max wrong. fp64 is fine so I don't need any fpdec changes.
Thanks for making fpdec!

**Comment by MarkSwanson** [comment]
Fyi fp64 has an accuracy ~= 16 digits after the decimal.

**Comment by mamrhein** [comment]
fpdec.rs uses an i128 to store the coefficient. This gives room for 38 decimal digits. 42 digits is definitely out of scope.

**Comment by mamrhein** [comment]
The original requirement is targeted at the quantities.rs crate. That crate can use different types for the numerical part of a quantity value, so maybe the solution could be another numerical type as optional dependency.
Please see [there](https://github.com/mamrhein/quantities.rs/issues/1).

**Comment by mamrhein** [comment]
Closing this as "will not implement".
